// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmxznwqhvbxdumzzezqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRteHpud3FodmJ4ZHVtenplenFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1OTQyNjgsImV4cCI6MjA2NjE3MDI2OH0.uSgds5ilE31ub_ji9EzdNH9co8SbTmhE2lUJTFIXJeU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);